### PR TITLE
Login

### PR DESCRIPTION
**Pull request by lannisterrr**
Added : Login Page - responsiveness added
Added :  Signup Page with custom checkbox
Added : switching between both the forms using JS.

### CODE REVIEW

**Review by raghav2110 — COMMENTED** [review]
The page looks really great. All the class name are on point. I guess overall good code , good to merge.

There is this red line below Login and Sign Up... Its a half line and not looking that great to me ...just a suggestion for it.

**Review by Hamdrive — COMMENTED** [review]
Great work done, very nice login/signup page created.

Would like to know why Wishlist HTML has been pushed onto this branch, as it is only titled and described for login/signup pages

**Comment by lannisterrr** [comment]
> Great work done, very nice login/signup page created.
> 
> Would like to know why Wishlist HTML has been pushed onto this branch, as it is only titled and described for login/signup pages

I am still figuring out branching in github , I did not merge the wishlist first before merging this , that's why the problem.

**Comment by lannisterrr** [comment]
> The page looks really great. All the class name are on point. I guess overall good code , good to merge.
> 
> There is this red line below Login and Sign Up... Its a half line and not looking that great to me ...just a suggestion for it.

I am going to add this to the component library so that it is customizable, but for this page , I want to practise ::after pauedo element , that's why I kept it.

**Pull request merged**
